Added drag and drop controller
WEKIT-ECS/MIRAGE-XR pull request #1002
Opened 2022-07-21 12:22 UTC by Alvareon

implemented drag and drop controller for the activity screen:

![draganddrop](https://user-images.githubusercontent.com/34060044/180212334-a8b5324e-5820-498a-922e-94f5fb2992f2.png)

2022-07-22 01:18 UTC, cawke requested changes

2022-07-22 01:18 UTC, cawke commented on Assets/MirageXR/Tests/NewUI/DragAndDropController.cs
> +                if (distance <= 15)
please name the number `15`

2022-07-22 10:46 UTC, Alvareon commented on Assets/MirageXR/Tests/NewUI/DragAndDropController.cs
> +                if (distance <= 15)
Done

2022-07-24 00:10 UTC, cawke approved these changes
ty

2022-07-24 01:51 UTC, merged