Profile settings
WEKIT-ECS/MIRAGE-XR pull request #1022
Opened 2022-08-23 10:00 UTC by robhillman97

Adds:

- log-in/out
- Register (redirect to webpage)
- Change Moodle server
- Change LRS server
- 
to profile page

 ![Logged In](https://user-images.githubusercontent.com/65968011/186130025-43d2a51b-8628-48d8-9929-9e110725ab9b.png)

![Logged Out](https://user-images.githubusercontent.com/65968011/186130039-8e0ba3b0-bed5-4042-a077-cb7a662b14c1.png)

![Change Moodle](https://user-images.githubusercontent.com/65968011/186130168-ed5cb5a7-f0a9-4254-a052-0b883d73a95d.png)

![Change LRS](https://user-images.githubusercontent.com/65968011/186130192-14db2f99-63c5-4e5f-80ee-fb96ac82b7ab.png)

2022-08-25 11:39 UTC, cawke requested changes

2022-08-25 11:39 UTC, cawke commented on Assets/MirageXR/Tests/NewUI/MoodleServersView.cs
> +        ChangeServerDomain("https://arete.ucd.ie");
move `"https://learn.wekit-ecs.com"` and `"https://arete.ucd.ie"` to `DBManager` as a const values

2022-08-25 11:39 UTC, cawke commented on Assets/MirageXR/Tests/NewUI/ProfileView.cs
> +        }
```suggestion
}
```

2022-08-25 11:39 UTC, cawke commented on Assets/MirageXR/Player/Scripts/Moodle/DBManager.cs
> +        public static int publicCurrentLearningRecordStore
reaplace with `Enum`

2022-08-25 11:39 UTC, cawke commented on Assets/MirageXR/Tests/NewUI/ProfileView.cs
> +    private void UpdateConectedLRS(int publicCurrentLearningRecordStore)
`int publicCurrentLearningRecordStore` reaplace with `Enum`

2022-08-25 11:39 UTC, cawke commented on Assets/MirageXR/Tests/NewUI/SelectLRS.cs
> +    private void ChangeRecordStore(int selectedLearningRecordStore)
`int selectedLearningRecordStore` reaplace with `Enum`

2022-08-31 18:30 UTC, cawke commented
@robhillman97 if you ready to review, just press `re-request review` button
![image](https://user-images.githubusercontent.com/20320355/187752914-95980f4e-bb91-4cb0-97ea-9e962ac8e2f7.png)

2022-09-08 09:20 UTC, fwild commented
Can we finalise this?

2022-09-13 23:23 UTC, cawke approved these changes
ty

2022-09-14 08:15 UTC, merged