Pick and place triggers
WEKIT-ECS/MIRAGE-XR pull request #1114
Opened 2022-11-23 09:34 UTC by robhillman97

Adds triggers to pick and place

closes #1064 & #1041

2022-11-24 14:46 UTC, cawke requested changes
Follow the code style.

2022-11-24 14:55 UTC, cawke reviewed
Please try running the tests locally.

2022-11-30 12:12 UTC, fwild commented
tests are now running through - though the previous test failures were in traced to "Tests.SetStartingPositionTests+<OnPlayerReset_RotationUpdated>d__4.MoveNext () [0x0013a] in /github/workspace/Assets/UnitTests/PlayModeTests/SetStartingPositionTests.cs" in the lines 101/127/154/181, so is either a glitch, or has been fixed elsewhere, but seems to have nothing to do with the code changes in this push.

2022-11-30 15:01 UTC, cawke requested changes

2022-11-30 15:01 UTC, cawke commented on Assets/MirageXR/Tests/NewUI/ContentListView_v2.cs
>                  _list.Add(obj);
```suggestion
                var obj = Instantiate(_contentListItemPrefab, _listContent);
                obj.Init(this, OnAnnotationSelected);
                _list.Add(obj);
```

2022-11-30 15:01 UTC, cawke commented on Assets/MirageXR/Tests/NewUI/ContentListItem_v2.cs
> +
```suggestion
    private System.Action<ToggleObject> _onListItemPressed;
```

2022-11-30 15:01 UTC, cawke commented on Assets/MirageXR/Tests/NewUI/ContentListItem_v2.cs
>      }
```suggestion
    public void Init(ContentListView_v2 parentView, System.Action<ToggleObject> onListItemPressed)
    {
        _parentView = parentView;
        _onListItemPressed = onListItemPressed;
        _btnSettings.onClick.AddListener(OnSettingsPressed);
        _btnListItem.onClick.AddListener(OnListItemPressed);
    }
```

2022-11-30 15:01 UTC, cawke commented on Assets/MirageXR/Tests/NewUI/ContentListItem_v2.cs
>      }
```suggestion
    private void OnListItemPressed()
    {
        _onListItemPressed?.Invoke(_content);
    }
```

2022-12-01 14:13 UTC, cawke approved these changes
ty

2022-12-01 14:16 UTC, merged