Tutorial activity is now unziped every time it is accessed
WEKIT-ECS/MIRAGE-XR pull request #1364
Opened 2023-04-26 08:27 UTC by robhillman97

the tutorial activity is now deleted and re-unziped if it already exists in local files

2023-04-26 22:54 UTC, cawke requested changes

2023-04-26 22:54 UTC, cawke commented on Assets/MirageXR/Tests/NewUI/ActivityListView_v2.cs
> +        var list = await LocalFiles.GetDownloadedActivities();
I think there is an easier option to load a specific activation. now you load all the local activations and choose one of them

2023-04-26 22:54 UTC, cawke commented on Assets/MirageXR/Tests/NewUI/ActivityListView_v2.cs
> +            if (t.id == "session-2023-02-24_11-18-29")
move to const

2023-04-27 21:19 UTC, BorisJov commented
Will merge this PR and fix requested changes upon merge to develop.

2023-04-27 21:19 UTC, merged