Fixes for HoloLens builds including Vuforia and OpenXR update closing #1170
WEKIT-ECS/MIRAGE-XR pull request #1450
Opened 2023-06-02 15:39 UTC by robhillman97

Includes;
- Update to use OpenXR
- Update to Vuforia 10.15.4
- Addition of world space console window
- Multiple fixes for various HoloLens issues detailed [here](https://github.com/WEKIT-ECS/MIRAGE-XR/milestone/17)

2023-06-06 15:14 UTC, cawke requested changes

2023-06-06 15:14 UTC, cawke commented on Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/ImageMarker Prefabs/ImageMarkerController.cs
> +        public IImageTarget target;
```suggestion
        public IImageTarget _target;
```

2023-06-06 15:14 UTC, cawke commented on Assets/MirageXR/Common/Scripts/Managers/ImageTarget/Manager/ImageTargetManagerVuforia.cs
>          }
activate **delayed initialization** and call the initialization here.

![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/20320355/406ba29f-c2c1-4198-a8e2-d22ee844d316)

```
        var vuforiaRuntime = VuforiaApplication.Instance;

        if (!vuforiaRuntime.IsInitialized)
        {
            vuforiaRuntime.Initialize();
            while (!vuforiaRuntime.IsInitialized)
            {
                await Task.Yield();
            }
        }
```

2023-06-06 15:14 UTC, cawke commented on Assets/MirageXR/Common/Scripts/Managers/ImageTarget/Target/ImageTargetVuforia.cs
> +    private Status _oldTargetStatus;
```
public class ImageTargetVuforia : ImageTargetBase
{
    private ImageTargetBehaviour _imageTargetBehaviour;
    private Status _oldTargetStatus;

    public ImageTargetBehaviour imageTargetBehaviour => _imageTargetBehaviour;

    protected override void TrackerInitialization()
    {
        _imageTargetBehaviour = GetComponent<ImageTargetBehaviour>();
        _oldTargetStatus = _imageTargetBehaviour.TargetStatus.Status;
        _imageTargetBehaviour.OnTargetStatusChanged += OnTrackableStatusChangedAction;
    }

    private void OnTrackableStatusChangedAction(ObserverBehaviour observerBehaviour, TargetStatus targetStatusChangeResult)
    {
        var statusChangeResult = targetStatusChangeResult.Status;
        OnStateChanged(ToTrackingState(_oldTargetStatus), ToTrackingState(statusChangeResult));
        _oldTargetStatus = statusChangeResult;
    }

    private static TrackingState ToTrackingState(Status state)
    {
        return state switch
        {
            Status.NO_POSE => TrackingState.Lost,
            Status.LIMITED => TrackingState.Limited,
            Status.EXTENDED_TRACKED => TrackingState.Limited,
            Status.TRACKED => TrackingState.Found,
            _ => throw new ArgumentOutOfRangeException(nameof(state), state, null)
        };
    }
}
```

2023-06-06 15:14 UTC, cawke commented on Assets/MirageXR/Player/Scripts/Managers/SpatialMapManager.cs
> +            }
```suggestion
                if (spatialMapMesh)
                {
                     spatialMapMesh.enabled = !editMode;
                }
            }
```

2023-06-06 15:14 UTC, cawke commented on Assets/MirageXR/Player/Scripts/Moodle/Login.cs
> +        public void showDeveloperOptions()
```suggestion
        public void ShowDeveloperOptions()
```

2023-06-06 15:33 UTC, cawke commented
Since you moved LoginMenu to ActivitySelectionMenu, remove CanvasUtility, as this will cause an error.

can i know the reason for moving the prefab? i'm just working on a similar window.

![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/20320355/77c16e88-a33b-4f46-9d63-f66270cde284)

2023-06-07 15:54 UTC, robhillman97 commented
> Since you moved LoginMenu to ActivitySelectionMenu, remove CanvasUtility, as this will cause an error.
> 
> can i know the reason for moving the prefab? i'm just working on a similar window.

We were making this object a child in code in login.cs line 50 with:

`           // make tha login panel a child of the activity list

            transform.position = loginPanelPosition.position;

            transform.rotation = loginPanelPosition.rotation;

            loginCanvas.transform.SetParent(FindObjectOfType<ActivitySelectionMenu>().transform);`

and I wanted to add a reference to the new console window with the login panel without using GameObject.find(); so I added this object to the scene and removed the code in login.cs

2023-06-08 18:43 UTC, cawke requested changes

2023-06-08 18:43 UTC, cawke commented on Assets/MirageXR/Common/Scripts/Managers/ImageTarget/Manager/ImageTargetManagerVuforia.cs
>          }
add check `if (!vuforiaRuntime.IsInitialized)` before `vuforiaRuntime.Initialize();`

```
        var vuforiaRuntime = VuforiaApplication.Instance;

        if (!vuforiaRuntime.IsInitialized)
        {
            vuforiaRuntime.Initialize();
            while (!vuforiaRuntime.IsInitialized)
            {
                await Task.Yield();
            }
        }
```

2023-06-08 22:23 UTC, cawke approved these changes

2023-06-28 09:14 UTC, merged