Hand positions saved when recording a ghost on HoloLens
WEKIT-ECS/MIRAGE-XR pull request #1632
Opened 2023-10-12 13:55 UTC by robhillman97

position of the tips of each fingers are now saved with the rest of ghost data

2023-10-13 11:33 UTC, fwild approved these changes

2023-10-16 01:49 UTC, cawke requested changes

2023-10-16 01:49 UTC, cawke commented on Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/GhostRecorder.cs
> +
pleace remove debug lines.
I don't think they're needed anymore.

2023-10-17 09:57 UTC, fwild approved these changes

2023-10-17 10:04 UTC, merged