implementing image caption
WEKIT-ECS/MIRAGE-XR pull request #1699
Opened 2023-12-03 22:37 UTC by shidende

2023-12-05 10:49 UTC, fwild commented
What about ImageCaptionEditor_v2.prefab and ImageCaptionPreview_v2.prefab? They are not in your pull request...? They were previously wrongly placed into the tests directory...?

2023-12-05 10:50 UTC, fwild requested changes
I think there are two files missing - please check!

2023-12-05 12:16 UTC, shidende commented
The two prefabs, ImageCaptionEditor_v2.prefab and ImageCaptionPreview_v2.prefab, have been added. They are now in the Assets/MirageXR/ContentTypes/Image/Editor/Mobile/NewUI/Prefabs/Content/ContentEditors folder.

2023-12-07 14:30 UTC, fwild approved these changes

2023-12-14 14:47 UTC, merged