1388 generate video caption
WEKIT-ECS/MIRAGE-XR pull request #1729
Opened 2024-01-11 03:28 UTC by shidende

This commit generate video augmentation using IBM Watson.

2024-01-18 11:32 UTC, cawke requested changes
![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/20320355/5f68c235-ba34-4401-a250-c461ae74a7cb)

There is no link to the script in the prefab.
because of this nothing works.

also write down a video explaining how it should work

2024-01-18 11:32 UTC, cawke commented on Assets/MirageXR/ContentTypes/Video/Editor/Mobile/CaptionGenerator.cs
> +        [SerializeField] private Button _stopButton;
remove region comments and sort the fields: first private fields with the [SerializeField] attribute, then just private fields. write the attribute on the same line as the field.

2024-01-18 11:32 UTC, cawke commented on Assets/MirageXR/ContentTypes/Video/Editor/Mobile/CaptionGenerator.cs
> +        [SerializeField] private Button _stopButton;
also follow the formatting throughout the file

2024-01-18 11:32 UTC, cawke commented on Assets/MirageXR/ContentTypes/Video/Editor/Mobile/VideoEditorView.cs
> +    [SerializeField] private GameObject VideoPreviePrefab;
if you write prefab in the field name, it means that you are going to store a link to the prefab that you are going to instantiate the object. For you, it’s just a link to a game object, which is confusing. rename the field

2024-01-18 11:32 UTC, cawke commented on Assets/MirageXR/ContentTypes/Video/Editor/Mobile/VideoEditorView.cs
> +    [SerializeField] private GameObject VideoPreviePrefab;
also follow the formatting and code style throughout the file

2024-01-24 23:12 UTC, shidende commented
Hi @cawke,
I have commited new changes to address your comments above. Also I have pushed the folder Demo that contains the video demostration.
Regards

2024-01-25 14:16 UTC, cawke commented
> Hi @cawke, I have commited new changes to address your comments above. Also I have pushed the folder Demo that contains the video demostration. Regards

thanks, but delete the video from the project and upload it somewhere so we can watch it, for example here.

2024-01-25 18:44 UTC, shidende commented
Here are the videos demo. 
https://github.com/WEKIT-ECS/MIRAGE-XR/assets/88036240/512ea7d0-4251-4bb4-a9fc-5b4673df8763
https://github.com/WEKIT-ECS/MIRAGE-XR/assets/88036240/18ffc2be-94fb-4eaa-8e74-f1c0a35eebcc
The video files already removed from the project.
CC: @cawke

2024-01-26 00:31 UTC, cawke commented
> Here are the videos demo. https://github.com/WEKIT-ECS/MIRAGE-XR/assets/88036240/512ea7d0-4251-4bb4-a9fc-5b4673df8763 https://github.com/WEKIT-ECS/MIRAGE-XR/assets/88036240/18ffc2be-94fb-4eaa-8e74-f1c0a35eebcc The video files already removed from the project. CC: @cawke

ty. can you send me the key in slack so I can check the work? (and write where to put it)
![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/20320355/aebb5a97-dcdf-46b0-a077-8a9c1b58de9e)

2024-01-29 11:03 UTC, cawke requested changes

2024-01-29 11:03 UTC, cawke commented on Assets/MirageXR/ContentTypes/Video/Editor/Mobile/CaptionGenerator.cs
> +            string pathToEnvFile = Application.dataPath + "/../ibm-credentials.env";
file storage and downloading is not possible in this way.
it simply won’t make it into the build for mobile devices.
I'll rewrite this.

file storage and downloading is not possible in this way.
it simply won’t make it into the build for mobile devices.
I'll rewrite this.

the file with the keys will need to be renamed to "caption-ibm-credentials.txt" and placed in the path "{Project_Root}\Assets\Resources"

2024-01-29 11:07 UTC, cawke approved these changes

2024-01-29 11:07 UTC, merged