1822 character interface with llm rag web services
WEKIT-ECS/MIRAGE-XR pull request #1911
Opened 2024-04-05 10:57 UTC by AKissMail

2024-04-05 11:06 UTC, fwild requested changes
The config should come from assets/resources/miragexrconfig.txt - maybe an opportunity to change that to JSON as well!

2024-04-09 10:24 UTC, cawke requested changes

2024-04-09 10:24 UTC, cawke commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +            UnityEngine.Debug.LogError("Speak");
only for debug?

2024-04-09 10:24 UTC, cawke commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +            UnityEngine.Debug.LogError("GetOptions");
remove

2024-04-09 10:24 UTC, cawke commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +            UnityEngine.Debug.LogError("Speak");
remove

2024-04-09 10:24 UTC, cawke commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +            UnityEngine.Debug.LogError("Config is done with " + _config.AiToken + _config.AiApiUrl + _config.AiPassword + _config.AiUsername);
remove

2024-04-09 10:24 UTC, cawke commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +            var r = new AiServicesConfig(apiURL, username, password);
```suggestion
            var config = new AiServicesConfig(apiURL, username, password);
```

2024-04-09 10:24 UTC, cawke commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +            var r = request.downloadHandler.text;
```suggestion
            var text = request.downloadHandler.text;
```

2024-04-09 10:24 UTC, cawke commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +            public TokenResponse(string t)
```suggestion
            public TokenResponse(string token)
```

2024-04-09 10:24 UTC, cawke commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +        private static async Task<string> AuthenticateUser(string apiURL, string user, string pass)
```suggestion
        private static async Task<string> AuthenticateUser(string apiURL, string user, string password)
```

2024-04-09 10:24 UTC, cawke commented on Assets/StreamingAssets/MirageXRConfig.txt
> +companyName:WEKIT ECS
is this an old file?

2024-04-09 10:24 UTC, cawke commented on Assets/Resources/MirageXRConfig.txt
> +companyName:WEKIT ECS
is this an old file?

2024-04-09 10:24 UTC, cawke commented on Assets/StreamingAssets/config.json
> +{
is this an old file?

2024-04-09 10:24 UTC, cawke commented on Assets/Resources/MirageXRConfig.json
> +  "AI_USERNAME": "admin" ,
you need to put your login password into a separate file. we cannot store private data in a public repository

2024-04-09 10:24 UTC, cawke commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +    public class AiServices
you wrote a service. now you need to write a manager that will initialize it (read the config and receive the login password) and manage this service.

2024-04-09 10:24 UTC, cawke commented on Assets/MirageXR/Player/Scripts/RootObject.cs
> +        private AiServices _aiServices;
there must be a manager who will manage this service

2024-04-09 10:24 UTC, cawke commented on Assets/MirageXR/ContentTypes/Character/Characters/ImageDisplayFiles/MagicParticle.mat
>  %TAG !u! tag:unity3d.com,2011:
I think this change was made by mistake. roll it back

2024-04-09 10:24 UTC, cawke commented on Assets/AddressableAssetsData/AssetGroups/Glyphs.asset
> +  - m_GUID: cea501bde7c9ce54dacac44c0cc2e01e
I think this change was made by mistake. roll it back

2024-04-09 10:24 UTC, cawke commented on Packages/packages-lock.json
>      "com.microsoft.mixedreality.openxr": {
I think this change was made by mistake. roll it back

2024-04-09 10:24 UTC, cawke commented on Assets/XR/Settings/Open XR Package Settings.asset
> ---- !u!114 &-9152892435972783649
I think this change was made by mistake. roll it back

2024-04-10 22:22 UTC, AKissMail commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +    public class AiServices
Okay, can you point me to an existing manager (MirageXR/Managers/?) and explain to me what it should do? I Podbay have to use the unity method like start() awake() and so on. Can we have a chat about what the manager should do?

2024-04-15 15:22 UTC, cawke requested changes

2024-04-15 15:22 UTC, cawke commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +                new MultipartFormDataSection("dfsdfjk", "dsfsdfkhsdfksdfh"),
I'm guessing it's the remnants of your testing?

2024-04-15 15:26 UTC, cawke commented on Assets/MirageXR/Scripts/AiServices/AiServices.cs
> +    public class AiServices
Now your AiServices class combines the work of both manager and service. in our case service should provide convenient access to work with your server (for example, your methods "Listen", "Think", "Speak" and "AuthenticateUser", although I would change the names). The manager should prepare (initialize) this service: read the keys (AiApiUrl, AiUsername, AiPassword) (we can't store these keys in the public repository, so put them in a file in the "Resources" folder), create an instance of the service, get and store the authentication token. Also all work with the service should be done through the manager, which means that in the manager you need to add methods "Listen", "Think", "Speak" inside which you will check the availability of the token, call the methods of the service and handle possible errors.

example https://github.com/WEKIT-ECS/MIRAGE-XR/blob/release_2.6/Assets/MirageXR/Scripts/OpenAI/OpenAIManager.cs

2024-05-06 22:32 UTC, AKissMail commented
@cawke 
I did not follow the result of our discussion 1 to 1, since I found a simpler solution (at least I think) which needs just an AI Model class and not 3 specific ones. That is the description for the last commit:
The AIManager and AI services have been refactored with a focus on how the Endpoint object will be deserialized.  A class that olds the Token and an AI Model has been added. The AI model will be held in a List for each endpoint and can be reached over a get method.

Old configuration files have been removed, and an error log has been added if the Authentication fails.

Open to discuss:
public async Task<List<OptionsResponse>> GetModelsAsync()
 is, from my point of view, obsolete and can be removed.
 
 I have one Issue, the 11
[Assets/MixedRealityToolkit.Generated/ProjectPreferences.asset](https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1911/files#diff-eaddd58c6f4b03814db0457cb5785ebee3c3f724799ea69d5456b69465712422) is a copy past version out of develop. It still shows up in the PR and I don't know how to remove it.

2024-05-09 09:15 UTC, cawke requested changes

2024-05-09 09:15 UTC, cawke commented on Assets/MirageXR/Managers/AIManager/AIManager.cs
> +        }
```suggestion
        private void SetModels(List<AIModel> endpointModels)
        {
            foreach (var model in endpointModels)
            {
                AddModelBasedOnEndpointName(model);
            }
        }
```

2024-05-09 09:15 UTC, cawke commented on Assets/MirageXR/Managers/AIManager/AIManager.cs
> +         */
```suggestion
```

2024-05-09 09:15 UTC, cawke commented on Assets/MirageXR/Managers/AIManager/AIManagerDataModel/Token.cs
> +}
```suggestion
namespace MirageXR.AIManagerDataModel
{
    public class Token
    {
         [JsonProperty("token")] public string Token { get; set; }
    }
}
```

2024-05-09 09:15 UTC, cawke commented on Assets/MirageXR/Managers/AIManager/AiServices.cs
> +            }
```suggestion
            {
                throw new HttpRequestException(
                    $"Error while receiving the result of the Think endpoint: {webRequest.error}");
            }
```

2024-05-09 09:15 UTC, cawke commented on Assets/MirageXR/Managers/AIManager/AiServices.cs
> +        }
```suggestion
            catch (Exception e)
            {
                throw new HttpRequestException("Error fetching or deserializing data: " + e.Message);
            }
        }
```

2024-05-09 09:15 UTC, cawke commented on Assets/MirageXR/Managers/AIManager/AiServices.cs
> +            }
```suggestion
            if (webRequest.result != UnityWebRequest.Result.Success)
            {
                throw new HttpRequestException($"Error while receiving the result of the Speak endpoint: {webRequest.error} {webRequest.result}");
            }
```

2024-05-09 09:15 UTC, cawke commented on Assets/MirageXR/Managers/AIManager/AiServices.cs
> +                UnityEngine.Debug.LogError($"Error while receiving the token: {request.error}!");
```suggestion
                throw new HttpRequestException($"Error while receiving the token: {request.error}!");
```

2024-05-09 09:15 UTC, cawke commented on Assets/MirageXR/Managers/AIManager/AiServices.cs
> +            return token;
```suggestion
            try
            {
                var token = JsonConvert.DeserializeObject<TokenData>(optionsText);
                return token.Token;
            }
            catch (Exception e)
            {
                throw new HttpRequestException("Error fetching or deserializing data: " + e.Message);
            }
```

2024-05-09 09:15 UTC, cawke commented on Assets/MirageXR/Managers/AIManager/AiServices.cs
> +        public static async Task<Token> AuthenticateUserAsync(string apiURL, string user, string password)
```suggestion
        public static async Task<string> AuthenticateUserAsync(string apiURL, string user, string password)
```

2024-05-09 09:15 UTC, cawke commented on Assets/MirageXR/Managers/AIManager/AIManager.cs
> +        private Token _token;
```suggestion
        private string _token;
```

2024-05-09 10:18 UTC, cawke approved these changes

2024-05-09 10:19 UTC, merged