A first basic build pipeline - just with a regular android build, not quest3 yet
WEKIT-ECS/MIRAGE-XR pull request #2040
Opened 2024-07-17 11:10 UTC by fwild

2024-07-25 13:02 UTC, cawke commented
to master?

2024-08-07 17:28 UTC, cawke requested changes

2024-08-07 17:28 UTC, cawke commented on Assets/MirageXR/Automation/Editor/LocalBuildPipeline.cs
> +        }
please fix the formatting

2024-08-08 11:37 UTC, BenediktHensen reviewed
The build works and it creates a apk file. I think everything should be fine with it, functionality-wise. One suggestion is to automatically fetch the included build scenes so that there still is a single source of truth to avoid confusion later on if we change the scenes in the build.

Initially, there were some Unity bugs and crashes with this branch, as Unity somehow did not initialize the buildtargetSettings.AssignedSettings reliably and it was always null, leading to a NullReferenceException when calling the XRPackageMetadataStore.AssignLoader. Sometimes, it would then initialize but then lead to crashes and corrupted XR Settings files during the build. However, after deleting the Library file and letting Unity re-generate the project, the pipeline now works reliably, so it was likely some old cache file that I had in the project.

2024-08-08 11:37 UTC, BenediktHensen commented on Assets/MirageXR/Automation/Editor/LocalBuildPipeline.cs
> +        public static string[] Scenes = { "Assets/MirageXR/Scenes/Start.unity", "Assets/MirageXR/Scenes/Player.unity", "Assets/MirageXR/Scenes/ActivitySelection.unity" };
We could use `EditorBuildSettings.scenes` https://docs.unity3d.com/ScriptReference/EditorBuildSettings-scenes.html instead of hardcoding the scene paths, as this is probably prone to breaking if we ever reorganize the folder structure. Then, the build pipeline would automatically take the scenes that are configured in the Build Window. If someones adds a new scene to the build in the future as they will probably overlook that the list in this script would need to be updated, too.

2024-08-11 08:41 UTC, fwild commented on Assets/MirageXR/Automation/Editor/LocalBuildPipeline.cs
> +        public static string[] Scenes = { "Assets/MirageXR/Scenes/Start.unity", "Assets/MirageXR/Scenes/Player.unity", "Assets/MirageXR/Scenes/ActivitySelection.unity" };
done

2024-08-11 08:42 UTC, merged