spatial ui (part 1)
WEKIT-ECS/MIRAGE-XR pull request #2083
Opened 2024-09-11 23:59 UTC by Alvareon

This is the first step of new spatial UI integration:

- added new screens to ui_kit;
- ui_kit moved to another place;
- updated the PlatformManager load objects;
- added root prefab ViewSpatial for the spatial UI;
- refactoring of prefab structure;
- added Extensions scripts; 
- added View for Main and Profile screens;

2024-09-12 08:15 UTC, fwild requested changes
Looks excellent to me - only about organisation: shouldn't Utility.UiKit be inside the MirageXR folder?

2024-09-12 11:04 UTC, cawke requested changes

2024-09-12 11:04 UTC, cawke commented on Assets/MirageXR/Player/Scripts/Spatial/MainScreenSpatialView.cs
> +        [SerializeField] private Button _button1;
change the name

2024-09-12 11:04 UTC, cawke commented on Assets/MirageXR/Design/UI_Elements/PNG/Icons/Spatial/Icon_ShowPass.png.meta
> +  maxTextureSize: 2048
change max resolution to 256

2024-09-12 19:42 UTC, Alvareon commented
> Looks excellent to me - only about organisation: shouldn't Utility.UiKit be inside the MirageXR folder?

UiKit moved into the MirageXR folder

2024-09-12 19:54 UTC, Alvareon commented on Assets/MirageXR/Player/Scripts/Spatial/MainScreenSpatialView.cs
> +        [SerializeField] private Button _button1;
fixed

2024-09-12 19:54 UTC, Alvareon commented on Assets/MirageXR/Design/UI_Elements/PNG/Icons/Spatial/Icon_ShowPass.png.meta
> +  maxTextureSize: 2048
fixed

2024-09-17 09:11 UTC, fwild approved these changes
please merge :)

2024-09-17 19:49 UTC, merged