Fix for issue #919
WEKIT-ECS/MIRAGE-XR pull request #920
Opened 2022-05-27 11:32 UTC by jafarigit

This will brings back the missing augmentation (image marker and pick and place) to the mobile version
Closes #919

2022-05-27 12:03 UTC, fwild requested changes
Can you please also fix the line 40 for hololens?

2022-05-27 12:04 UTC, fwild commented
Or was the hololens not affected?

2022-05-27 15:12 UTC, fwild approved these changes

2022-05-29 12:32 UTC, cawke commented on Assets/MirageXR/Player/Scripts/Managers/BrandManager.cs
> +    private readonly string[] spareListOfAugmentations = { "image", "video", "audio", "ghost", "label", "act", "vfx",  "model", "character", "pickandplace", "imagemarker", "plugin" };
is there any reason to keep two identical lists or can we keep just one? 
```
BrandManager.spareListOfAugmentations
BrandConfiguration.spareListOfAugmentations
```

2022-05-29 23:00 UTC, merged