LRS dropdown
WEKIT-ECS/MIRAGE-XR pull request #978
Opened 2022-06-14 09:36 UTC by robhillman97

Added drop down to settings menu's to allow users to switch between WEKIT and ARETE LRS

closes #914

2022-06-15 11:15 UTC, cawke requested changes
Add screenshots of what the menu now looks like and screenshots of what you have changed in the prefabs

2022-06-15 11:15 UTC, cawke commented on Assets/MirageXR/Player/Scripts/Mobile/Popup/SettingsView.cs
> +    [SerializeField] private Dropdown _LRSDropdown;
fix the name

2022-06-15 11:15 UTC, cawke commented on Assets/MirageXR/Player/Scripts/Managers/EventManager.cs
> +        }
in the future we need to get rid of event creation. For now, let it be

2022-06-15 11:42 UTC, robhillman97 commented
> 

This has currently only been added to the HoloLens and old mobile UI. I am looking at how to add this to the new UI at the moment. 

![LRS Dropdown](https://user-images.githubusercontent.com/65968011/173817212-77cdd592-89dc-450e-9408-19d0d85b0b53.png)

![LRS Dropdown HL](https://user-images.githubusercontent.com/65968011/173818945-874b30d0-7e4e-4ccd-8e5e-adea1a791c33.png)

2022-06-16 09:21 UTC, cawke approved these changes
Thanks

2022-06-16 09:51 UTC, merged